### PR TITLE
Build with autotools and package with Debian

### PR DESCRIPTION
**Pull request by hashbrowncipher**
We previously left it as an exercise to the reader to compile jvmquake against their Java version, but it appears to me that the jvm.h and jvmti.h interfaces are stable across JDK releases (observed by diffing the header files across different JDKs). As such, it should be possible to compile once, run many places (i.e. across various JVMs, but confined to a given architecture).

This PR adds rudimentary autotools functionality to find a JVM to compile against and to produce jvmquake as a dynamic library which can be installed into a `/usr/lib` directory and then used by any JVM on the system.

### CODE REVIEW

**Comment by jolynch** [comment]
Ah cool so this would allow us to potentially publish jvmquake-<arch>-<jvm>.so builds as well, and give a path forward for projects that want to generate their own `.so` builds for including as well (e.g. potentially Cassandra in CASSANDRA-15214).

Looks like we just need to fixup the test suites, build with jdk8 and then test with jdk8 and jdk11. I imagine some of the GC arguments won't apply in J11 as well so gotta figure that out.

**Comment by hashbrowncipher** [comment]
Here's a commit that builds on Xenial: https://github.com/Netflix-Skunkworks/jvmquake/commit/19406e5bc0abc5ffa6b31c3655190d336b684355

Alternatively, I believe a libjvmquake.so produced on Bionic should work just fine on Xenial. In fact, it should work on anything with a libc version >=2.7, so a build produced on Bionic should work on every Ubuntu down to Hardy (2008).

**Comment by jolynch** [comment]
@hashbrowncipher what do you think about the alternative in #6 ?

**Comment by hashbrowncipher** [comment]
Closed per discussion in #6.

**Pull request closed without merging**
